#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by SEEMAN version 7m
#  in conjunction with Tcl version 8.6
#    Aug 09, 2021 06:29:27 AM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import DataGridTest_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#fffaf0'  # X11 color: '{floral white}'
        _fgcolor = '#2208cc'  # Closest X11 color: '{medium blue}'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("799x364")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(0,  0)
        top.title("New Toplevel")
        top.configure(background="#fffaf0")
        top.configure(highlightbackground="#f2f2f2")
        top.configure(highlightcolor="black")

        self.top = top

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(x=5, y=11, height=290, width=785)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#fffaf0")
        self.Frame1.configure(highlightbackground="#f2f2f2")

        self.Custom1 = DataGridTest_support.Custom(self.Frame1)
        self.Custom1.place(x=0, y=0, height=290, width=785)

        self.lblCellValue = tk.Label(self.top)
        self.lblCellValue.place(x=20, y=320, height=18, width=249)
        self.lblCellValue.configure(activebackground="#ffffff")
        self.lblCellValue.configure(background="#fffaf0")
        self.lblCellValue.configure(disabledforeground="#b6b6b6")
        self.lblCellValue.configure(foreground="#2208cc")
        self.lblCellValue.configure(highlightbackground="#f2f2f2")
        self.lblCellValue.configure(text='''label''')

        self.btnLoad = tk.Button(self.top)
        self.btnLoad.place(x=315, y=320, height=24, width=90)
        self.btnLoad.configure(activebackground="#ffffcd")
        self.btnLoad.configure(activeforeground="#2208cc")
        self.btnLoad.configure(background="#fffaf0")
        self.btnLoad.configure(command=DataGridTest_support.btnLoad_Click)
        self.btnLoad.configure(disabledforeground="#b6b6b6")
        self.btnLoad.configure(foreground="#2208cc")
        self.btnLoad.configure(highlightbackground="#fffaf0")
        self.btnLoad.configure(pady="0")
        self.btnLoad.configure(text='''Load Data''')

        self.btnClear = tk.Button(self.top)
        self.btnClear.place(x=440, y=319, height=24, width=90)
        self.btnClear.configure(activebackground="#ffffcd")
        self.btnClear.configure(activeforeground="#2208cc")
        self.btnClear.configure(background="#fffaf0")
        self.btnClear.configure(command=DataGridTest_support.btnClear_Click)
        self.btnClear.configure(disabledforeground="#b6b6b6")
        self.btnClear.configure(foreground="#2208cc")
        self.btnClear.configure(highlightbackground="#fffaf0")
        self.btnClear.configure(pady="0")
        self.btnClear.configure(text='''Clear''')

def start_up():
    DataGridTest_support.main()

if __name__ == '__main__':
    DataGridTest_support.main()




