#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by SEEMAN version 7m
#  in conjunction with Tcl version 8.6
#    Aug 09, 2021 08:24:46 AM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import new_support

class Window_I:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#f5deb3'  # X11 color: 'wheat'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}'
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2'

        top.geometry("329x245+911+395")
        top.minsize(1, 1)
        top.maxsize(1905, 1050)
        top.resizable(1,  1)
        top.title("Window I")
        top.configure(background="#f5deb3")
        top.configure(highlightbackground="#f5deb3")
        top.configure(highlightcolor="black")

        self.top = top

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.365, rely=0.694, height=37, width=72)
        self.Button1.configure(activebackground="#f4bcb2")
        self.Button1.configure(background="#f5deb3")
        self.Button1.configure(command=new_support.quit)
        self.Button1.configure(disabledforeground="#b8a786")
        self.Button1.configure(font="-family {DejaVu Sans Mono} -size 14")
        self.Button1.configure(highlightbackground="#f5deb3")
        self.Button1.configure(text='''Quit''')

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.213, rely=0.286, height=37, width=171)
        self.Button2.configure(activebackground="#f4bcb2")
        self.Button2.configure(background="#f5deb3")
        self.Button2.configure(command=new_support.start2)
        self.Button2.configure(disabledforeground="#b8a786")
        self.Button2.configure(font="-family {DejaVu Sans Mono} -size 14")
        self.Button2.configure(highlightbackground="#f5deb3")
        self.Button2.configure(text='''Create Window''')

class Window_II:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#f5deb3'  # X11 color: 'wheat'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}'
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("524x350+335+334")
        top.minsize(1, 1)
        top.maxsize(1905, 1050)
        top.resizable(1,  1)
        top.title("Window II")
        top.configure(background="#f5deb3")
        top.configure(highlightbackground="#f5deb3")
        top.configure(highlightcolor="black")

        self.top = top
        self.greeting = tk.StringVar()
        self.greeting.set('Greeting')
        self.t = tk.IntVar()

        self.Button1_1 = tk.Button(self.top)
        self.Button1_1.place(relx=0.115, rely=0.429, height=37, width=83)
        self.Button1_1.configure(activebackground="#f4bcb2")
        self.Button1_1.configure(background="#f5deb3")
        self.Button1_1.configure(command=new_support.close)
        self.Button1_1.configure(disabledforeground="#b8a786")
        self.Button1_1.configure(font="-family {DejaVu Sans Mono} -size 14")
        self.Button1_1.configure(highlightbackground="#f5deb3")
        self.Button1_1.configure(text='''Close''')

        self.TProgressbar1 = ttk.Progressbar(self.top)
        self.TProgressbar1.place(relx=0.42, rely=0.743, relwidth=0.191
                , relheight=0.0, height=19)
        self.TProgressbar1.configure(variable=self.t)

        self.Button2_1 = tk.Button(self.top)
        self.Button2_1.place(relx=0.387, rely=0.429, height=37, width=105)
        self.Button2_1.configure(activebackground="#f4bcb2")
        self.Button2_1.configure(background="#f5deb3")
        self.Button2_1.configure(command=new_support.hide)
        self.Button2_1.configure(disabledforeground="#b8a786")
        self.Button2_1.configure(font="-family {DejaVu Sans Mono} -size 14")
        self.Button2_1.configure(highlightbackground="#f5deb3")
        self.Button2_1.configure(text='''Hide W1''')

        self.Button3 = tk.Button(self.top)
        self.Button3.place(relx=0.702, rely=0.429, height=37, width=94)
        self.Button3.configure(activebackground="#f4bcb2")
        self.Button3.configure(background="#f5deb3")
        self.Button3.configure(command=new_support.show)
        self.Button3.configure(disabledforeground="#b8a786")
        self.Button3.configure(font="-family {DejaVu Sans Mono} -size 14")
        self.Button3.configure(highlightbackground="#f5deb3")
        self.Button3.configure(text='''Show W1''')

        self.Message1 = tk.Message(self.top)
        self.Message1.place(relx=0.363, rely=0.229, relheight=0.094
                , relwidth=0.242)
        self.Message1.configure(background="#f5deb3")
        self.Message1.configure(font="-family {DejaVu Sans Mono} -size 14")
        self.Message1.configure(highlightbackground="wheat")
        self.Message1.configure(text='''Greeting''')
        self.Message1.configure(textvariable=self.greeting)
        self.Message1.configure(width=127)

def start_up():
    new_support.main()

if __name__ == '__main__':
    new_support.main()




