#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by SEEMAN version 7m
#  in conjunction with Tcl version 8.6
#    Aug 09, 2021 06:31:24 AM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import tksheetGUI_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("937x648+486+186")
        top.minsize(1, 1)
        top.maxsize(3585, 1050)
        top.resizable(0,  0)
        top.title("New Toplevel")
        top.configure(highlightbackground="wheat")
        top.configure(highlightcolor="black")

        self.top = top

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(x=0, y=60, height=575, width=935)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(highlightbackground="wheat")

        self.Custom1 = tksheetGUI_support.Custom(self.Frame1)
        self.Custom1.place(x=0, y=0, height=575, width=935)

        self.Button1 = tk.Button(self.top)
        self.Button1.place(x=20, y=20, height=29, width=119)
        self.Button1.configure(activebackground="#ffffcd")
        self.Button1.configure(command=tksheetGUI_support.on_btnLoad)
        self.Button1.configure(disabledforeground="#b8a786")
        self.Button1.configure(highlightbackground="wheat")
        self.Button1.configure(text='''Load CSV''')

        self.Button2 = tk.Button(self.top)
        self.Button2.place(x=820, y=20, height=29, width=89)
        self.Button2.configure(activebackground="#ffffcd")
        self.Button2.configure(command=tksheetGUI_support.on_btnExit)
        self.Button2.configure(disabledforeground="#b8a786")
        self.Button2.configure(highlightbackground="wheat")
        self.Button2.configure(text='''Exit''')

def start_up():
    tksheetGUI_support.main()

if __name__ == '__main__':
    tksheetGUI_support.main()




