#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by SEEMAN version 7.4
#  in conjunction with Tcl version 8.6
#    Jul 31, 2022 07:44:48 PM +0430  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import busycursor_support

def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(busycursor_support.root, tearoff=0)
        Popupmenu1.configure(activebackground="#f4bcb2")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="black")
        Popupmenu1.configure(background="#45d84f")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#b8a786")
        Popupmenu1.configure(font="-family {Nimbus Sans L} -size 14")
        Popupmenu1.configure(foreground="#000000")
        sub_menu = tk.Menu(Popupmenu1,
                activebackground="#f4bcb2",
                activeborderwidth=1,
                activeforeground="#000000",
                background="#45d84f",
                borderwidth=1,
                disabledforeground="#a3a3a3",
                font="-family {Nimbus Sans L} -size 14",
                foreground="#000000",
                tearoff=0)
        Popupmenu1.add_cascade(menu=sub_menu,
                label="NewCascade")
        sub_menu.add_command(
                label="NewCommand")
        Popupmenu1.post(event.x_root, event.y_root)

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = 'wheat'  # X11 color: #f5deb3
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}'
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2'
        _tabfg1 = 'black' 
        _tabfg2 = 'black' 
        _tabbg1 = 'grey75' 
        _tabbg2 = 'grey89' 
        _bgmode = 'light' 

        top.geometry("600x450")
        top.minsize(120, 1)
        top.maxsize(1905, 1050)
        top.resizable(1,  1)
        top.title("Busy Cursor Example")
        top.configure(background="wheat")
        top.configure(highlightbackground="wheat")
        top.configure(highlightcolor="black")

        self.top = top

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.383, rely=0.333, height=30, width=41)
        self.Button1.configure(activebackground="#f4bcb2")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="wheat")
        self.Button1.configure(command=busycursor_support.run)
        self.Button1.configure(disabledforeground="#b8a786")
        self.Button1.configure(font="-family {DejaVu Sans} -size 12")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="wheat")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Run''')

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.4, rely=0.667, height=30, width=42)
        self.Button2.configure(activebackground="#f4bcb2")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background="wheat")
        self.Button2.configure(command=busycursor_support.quit)
        self.Button2.configure(disabledforeground="#b8a786")
        self.Button2.configure(font="-family {DejaVu Sans} -size 12")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="wheat")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Quit''')

def start_up():
    busycursor_support.main()

if __name__ == '__main__':
    busycursor_support.main()




